language: php
os:
  - linux
dist: xenial

cache:
  directories:
    - "${HOME}/.composer/cache"

php:
    - 7.3
    - 7.2
    - 7.1

install:
    - travis_retry composer update --no-interaction --prefer-source

script:
    - composer run-script pipeline

after_success:
    - bash <(curl -s https://codecov.io/bash)
